### ISSUE TITLE
Update chef recipes

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-chef#13]
Hello team,

I've noticed recipes for Chef are not properly updated.
In many cases they are missing parameters and options like, for example, the ability to add an agent group at registration time.

Regards.

**Comment by jm404** [comment]
Hi team!

In order to improve current recipes and add new ones, the repository will be refactored to split Agent and Manager into different cookbooks. This will make the implementation of new recipes and tests easier and will follow chef-repo standards easing the upgrade process for users.

You can check it here: #17 .

Regards!
Jose

**Comment by manuasir** [comment]
Done here #22
