### ISSUE TITLE
Update references to deprecated authd options and consider the new ones.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-chef#136]
As part of epic [#9550](https://github.com/wazuh/wazuh/issues/9550) it is required to add new configuration options to the authd module to decide what actions should be taken during an agent replacement. That being said, it is required to modify the following file considering the new configuration block and the deprecated options.

```
<force>
  <enabled>yes|no</enabled>
  <key_mismatch>yes|no</key_mismatch>  
  <disconnected_time enabled="yes"|"no">1h</disconnected_time>  
  <after_registration_time>1h</after_registration_time>  
</force>
```
- cookbooks/wazuh_manager/attributes/auth.rb

**Comment by vcerenu** [comment]
We have a problem with the creation of the disconnected_time tag, which is different at the beginning and at the end.
The generation code of the same should be the following:
```
     'force' => {
         'enabled' => 'yes',
         'key_mismatch' => 'yes',
         'disconnected_time enabled? "yes"' => '1h',
         'after_registration_time' => '1h'
     },
```

The problem is that the result it generates is the following:

```
<force>
   <enabled> yes </enabled>
   <key_mismatch> yes </key_mismatch>
   <disconnected_time enabled = "yes"> 1h </disconnected_time> enabled = "yes" & gt;
   <after_registration_time> 1h </after_registration_time> </force>
```

Talking to the people at Core Dev they tell me that we can bypass these tags in the ossec.conf file, which would result in the behavior we are adding.

It proceeds to verify which alternative we will use.
