### ISSUE TITLE
Feature request: Chef recipe for Wazuh Agent installation in macOS

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh-chef#156]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.9 | Agent | Agent | Chef deployment | macOS |

Hello team!

By checking the Wazuh agent installation recipe for Chef, [here](https://github.com/wazuh/wazuh-chef/blob/master/cookbooks/wazuh_agent/recipes/agent.rb) I noticed there's no support for macOS agents:
![image](https://user-images.githubusercontent.com/29696136/198131627-1d818102-37f9-4e7a-b740-2a95c5b2b23c.png)

We need a way to deploy the agent into macOS systems using Chef.

**Comment by vcerenu** [comment]
An analysis of the current operation of the recipe for the installation of `Wazuh Agent` within the current repository was carried out. It performs the installation of Wazuh by calling the package manager that corresponds to the version of the operating system in which it is being installed.

The current installation method of `Wazuh agent` on `MacOs` within our documentation has been revised. It does not use a package manager; rather, the installation is done by downloading the installation package and performing the installation by hand.

An option for `MacOs` was added to the installation procedure, which will carry out actions different from those carried out in the other OS, in addition to ignoring configurations that are made at the repository level, which were not taken into account at the time. to install currently and the default option was a method that is incompatible with `MacOs`, so an option must be added to skip this check.

Created branch [macos-agent-install](https://github.com/wazuh/wazuh-chef/tree/macos-agent-install), which currently has the changes. An installation test is missing to verify that both the `Wazuh Agent` installation and its configuration after installation are correct.

**Comment by vcerenu** [comment]
Changes were made to all `wazuh_agent` recipe files, especially to the `agent.rb` recipe, which contains the agent installation procedure for all supported operating systems.

The variables that did not coincide with the deployment in `Linux` and the orders on starting and restarting the services, which have their own utilities within `Chef`, were modified.

The modification remains on the branch  [macos-agent-install](https://github.com/wazuh/wazuh-chef/tree/macos-agent-install) so that they can verify and test it. On our side, installation tests were carried out on `macOS` environments and the correct execution and registration of agents in manager were confirmed.

![image](https://user-images.githubusercontent.com/56500015/199582114-c2a88034-b450-4b8a-9610-37ac59d599eb.png)

**Comment by alberpilot** [comment]
The compare:
https://github.com/wazuh/wazuh-chef/compare/4.3...macos-agent-install

Waiting for @maumrsms feedback to validate. 
Blocked until then.
