### ISSUE TITLE
Use `verify-agent-conf`

### ISSUE THREAD

**Issue by curiositycasualty** [wazuh/wazuh-chef#29]
This is more just informational for @jm404 since I just stumbled across it myself:
[As of chef `12.5.1`](https://github.com/chef/chef/blob/master/CHANGELOG.md#1251), you can use `verify` in the `template` resource as follows:
```
include_recipe 'wazuh::manager'

template "#{dir}/etc/shared/default/agent.conf" do
  source 'manager_agent.conf.erb'
  owner 'ossec'
  group 'ossec'
  mode '0644'
  verify '/var/ossec/bin/verify-agent-conf -f %{path}'
end
```

**Comment by curiositycasualty** [comment]
As seen: https://github.com/chef-cookbooks/openssh/pull/120

**Comment by jm404** [comment]
Hi @curiositycasualty ,

I reviewed the Chef changelog and the OpenSSH example you provided. It gives a great way to verify the modifications of configurations files. Will surely implement it on new release (#28) and will let you know!

I really appreciate your mention to give me some good examples and ideas.

Best regards!

Jose

**Comment by jm404** [comment]
Hi @curiositycasualty ,

I've investigated the `verify` parameter and tested it in different situations. If the code block in the `verify` parameter resolves to *false*, the whole chef-run process is stopped. 

I understand it as a stopping condition but can't see a fit in our installation process for it.

Let me mention you the official docs in case you want to check them: https://docs.chef.io/resource_template.html 

Anyway, I appreciate your mention and feel free to open any other issue with any other issue, question or improvement.

Best Regards,

Jose

**Comment by curiositycasualty** [comment]
@jm404 What's the use case for *not* wanting to stop the run if the manager's shared `agent.conf` is invalid according to `verify-agent-conf`? I would think you wouldn't want to write an unverified `.conf` file into place. Like Salt's [`check_cmd`](https://docs.saltstack.com/en/latest/ref/states/requisites.html#check-cmd), the `verify` stuff is run against a file before it gets placed at the final location specified in the `template` resource.

Without this, you can have an invalid `agent.conf` which the manager will silently refuse to push to the agents.

**Comment by jm404** [comment]
Hi @curiositycasualty ,

The Wazuh Manager cookbook implements Gyoku in order to give the user flexibility when configuring the *ossec.conf* file. The main reason for using Gyoku is that makes the installation completely flexible, you can declare any attribute you want and it will be translated to XML and properly inserted in *ossec.conf* file.

Same happens with *agent.conf*, I think that it's way more difficult and a worse approach to generate that file using a template because it makes the installation process much less flexible and harder to customize.

The solution you proposed is completely right, stopping the manager from pushing a wrong configuration file makes a lot of sense but we can't benefit from the `verify` parameter since we don't use templates for *ossec.conf* and *agent.conf* is not implemented yet.

I'm thinking about the implementation of verification blocks to make sure the config files are properly declared.

Looking forward to your response!

Best Regards,

Jose

**Comment by curiositycasualty** [comment]
@jm404 [It would seem that the Gyoku approach introduces its own challenges to flexibility](https://github.com/wazuh/wazuh-chef/issues/10). But also, the `verify` property applies to the `file` resource as well, which is the resource being used to write `ossec.conf`: https://github.com/wazuh/wazuh-chef/blob/21332f911bfebc4a692066c56ad4ee48dba73281/cookbooks/wazuh_agent/recipes/common.rb#L38-L50

**Comment by jm404** [comment]
Hi @curiositycasualty ,

I checked the official docs for `file` resource and as you stated it implements the `verify` parameter. I will keep it in mind when implementing `agent.conf`. I opened an issue related to this: https://github.com/wazuh/wazuh-chef/issues/31

We've had no problems with nesting Gyoku as you can check [here](https://github.com/wazuh/wazuh-chef/blob/3.9/cookbooks/wazuh_manager/attributes/command.rb#L1-L14). Anyway we will review that issue in `3.9` branch.

As always, thank you for contributing!

Regards,

Jose

**Comment by curiositycasualty** [comment]
In the link you supplied, there's an array of hashes, which is valid ruby even when the hashes are duplicates of each other. In the link I supplied, there's a hash with multiple, duplicate keys. I think the submitter for https://github.com/wazuh/wazuh-chef/issues/10 was referring to the fact that `{... feed: {...}, feed:{...} ...}` is an invalid ruby hash due to duplicate keys, but if Gyoku-ize-able, would produce valid xml (`<thing>...<feed>...</feed>...<feed>...</feed>...</thing>`).

But that's a different conversation, I'll close this one out.
