### ISSUE TITLE
Configure default Elastic Stack attributes and verify them

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#49]
Hi all,

Some of the attributes of Elastic Stack initialize to an invalid value like:

https://github.com/wazuh/wazuh-chef/blob/fe773bc632a51431a6dbfd8a3de942b4c585d425/cookbooks/wazuh_elastic/attributes/elasticsearch.rb#L20 

This has been done to prevent unknown misconfigurations when deploying since declaring this attribute and related ones to `127.0.0.1` would set up the stack properly but the user could ignore that configuration.

In an actual way, we ensure the user consciously set his desired IP/domain for every component.

#### Community, we need you!

It`s important to us to determine which default case is better in your opinion, do you prefer to configure after setup with default parameters or preconfigure variables and then run the setup?

Let us know by commenting below!

#### Verify variables before run

Regardless of the option, we choose in the previous scenario, it's required to add verification of those parameters.

In order to avoid said problems some, the pre-check of the variables must be done

#### Tasks

- [x] Implement pre-run verification of the attributes (not null, variable type, etc...)

- [x] Test changes

- [x] Update README.md

Best regards!

Jose

**Comment by rshad** [comment]
Hi all!

As we've been waiting for almost 5 months to receive opinions from our community members about the raised question, we found ourselves obligated to proceed with the approach we think that would fit better for most cases, however, we are always open for new changes proposed by our community members at any time, so **Wazuh Community**, please don't hesitate to propose new ideas; that makes us better! 

In order to have a valid installation for Elasticsearch by default, we proposed to set the IP `0.0.0.0` as Elasticsearch endpoint IP in `elasticsearch.yml` and `localhost` in other components configuration files, those which are connected to Elasticsearch, like `Filebeat`.

 _Always taking **Single Host**`approach as the default one_

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

Changes are applied to the branch: [feature-49-elasticsearch-ip](https://github.com/wazuh/wazuh-chef/tree/feature-49-elasticsearch-ip).

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

Changes are applied and tested successfully. Check https://github.com/wazuh/wazuh-chef/commit/4104bc863535f6fecb33af25b2b92233b44bf62e & https://github.com/wazuh/wazuh-chef/commit/c6e3fa265590fa46f8c5137b59f237004664f128.

- We adapted the value Elasticsearch default endpoint IP:
https://github.com/wazuh/wazuh-chef/blob/c6e3fa265590fa46f8c5137b59f237004664f128/cookbooks/wazuh_elastic/attributes/elasticsearch.rb#L20

- We adapted Filebeat's elastic search output IP:
https://github.com/wazuh/wazuh-chef/blob/c6e3fa265590fa46f8c5137b59f237004664f128/cookbooks/wazuh_filebeat/attributes/default.rb#L10

- We parameterize `filebeat.yml` template.
https://github.com/wazuh/wazuh-chef/blob/c6e3fa265590fa46f8c5137b59f237004664f128/cookbooks/wazuh_filebeat/templates/default/filebeat.yml.erb#L15

https://github.com/wazuh/wazuh-chef/blob/c6e3fa265590fa46f8c5137b59f237004664f128/cookbooks/wazuh_filebeat/recipes/filebeat.rb#L46-L52

Kr,

Rshad
