### ISSUE TITLE
Wazuh_Elastic  and Wazuh_filebeat not checked into to Chef Supermarket?

### ISSUE THREAD

**Issue by labkey-stuartm** [wazuh/wazuh-chef#5]
Hello,

Do you plan to check in the Wazuh_elastic and Wazuh_filebeat cookbooks into the Chef Supermarket?

**Comment by jlruizmlg** [comment]
Hi @labkey-stuartm yes, we will do as soon as we can.

**Comment by labkey-stuartm** [comment]
Thank you.

**Comment by sc7565** [comment]
Just checking... when do you guys intent to publish the cookbooks to Chef Supermarket as we in middle of implementation and would like to include them @jlruizmlg

**Comment by rshad** [comment]
Hi all!

Today we made a Demo about the best way to maintain and share Wazuh Chef's cookbooks, roles, etc.

Steps to follow:

1- We first should create an account in Chef https://manage.chef.io/signup
- - Save our private key file

2- Grant `Access Permission` for Chef Supermarket so we then would be able to upload cookbooks to Chef Supermarket.

3- Create an organization for Wazuh.
- - Add the corresponding users with the proper permissions.
- - Download the client validation key.
- - Download Knife configuration file.

**In local machine and inside our wazuh-chef folder** 

4- Create folder `.chef`

5- Copy Knife configuration file into `wazuh-chef/.chef` : knife.rb

```ruby
# See http://docs.chef.io/config_rb_knife.html for more information on knife configuration options

current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "<username>"
validation_client_name   "<organiztion name>-validator"
validation_key           "#{current_dir}/<organiztion name>-validator.pem"
client_key               "#{current_dir}/<user key file name>.pem"
chef_server_url          "https://api.chef.io/organizations/<organiztion name>"
cookbook_path            ["#{current_dir}/../cookbooks"]
```

6- Copy the `Client Validation Key` into `wazuh-chef/.chef` : <client name>.pem

- - A default one is created automatically.

7- Copy our user `private key` into  `wazuh-chef/.chef` : <key file name>.pem

Then we are ready to upload and share.

**Uploading to the Organization**

Upload the entire chef-repo

Browse to the top level of the chef-repo and enter:
```
$ knife upload .
```

or from anywhere in the chef-repo, enter:
```
$ knife upload /
```
to upload all cookbooks and data bags, plus all roles and environments that are stored as JSON data. (Roles and environments stored as Ruby data will not be uploaded.)


![image](https://user-images.githubusercontent.com/19154337/68884633-d951a100-0713-11ea-9793-83b32bf08e01.png)


For more details, check [here](https://docs.chef.io/knife_upload.html)


`Note`: Uploading the files `cookbooks, roles, etc ..` to the organization is not equivalent to upload the cookbook to the supermarket, this needs to be done separately, as follows:

```
knife supermarket share "<cookbook name>" -o <path to cookbooks>
```

**Issue**

We got error message when trying to unshare a cookbook from the supermarket owned by us:
```
ERROR: Forbidden: You must be the maintainer of <...>to unshare it.
```

We thought that maybe it's related because we didn't specify ourselves as maintainers for the shared cookbooks but it either works with the ones we maintain.

This issue is already reported here: https://github.com/chef/chef/issues/8056


Kr,

Rshad
